name = "Psi"
license = "GPL-3.0 License"
licenselink = "https://github.com/lukeorth/poison/blob/master/LICENSE.md"
description = "A pragmatic Hugo theme for bloggers.  Based on the classic \"Hyde\" design by mdo."
min_version = "0.41.0"

[author]
    name = "Luke Orth"
    homepage = "https://lukeorth.com"

# If Porting existing theme
[original]
    author =  "mdo"
    homepage = "http://markdotto.com/"
    repo = "https://www.github.com/mdo/hyde"
